# Generated by Django 4.2.1 on 2024-04-13 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationslinks',
            name='cat',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='education.category', verbose_name='Категория'),
        ),
    ]
